server:
  port: 9090

master:
  user:
    name: IRIS
    email: abIris@gmail.com

spring:
  application:
    name: Health-Care
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/healthcare_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: <Gmail username>
    password: <Gmail password>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
